[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[mounts]]
source = "workspace"
target = "/workspace"

[[mounts]]
source = "cache"
target = "/cache"
